import type { Metadata } from "next"

import "../styles/globals.css"
import { Toaster } from "@/components/ui/sonner"
import { Poppins } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes"
import { ViewTransitions } from "next-view-transitions"

import "../styles/globals.css"
import { Toaster } from "@/components/ui/sonner"
import { Poppins } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "next-themes"
import { ViewTransitions } from "next-view-transitions"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // Note! If you do not add suppressHydrationWarning to your <html> you will get warnings because next-themes updates that element. This property only applies one level deep, so it won't block hydration warnings on other elements.
    <ViewTransitions>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-background font-poppins antialiased",
            Poppins.variable
          )}
        >
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  )
}
